[deps] Added support for Django 3.2 and Django 4.0a #122
openwisp/django-x509 pull request #125
Opened 2021-10-22 17:03 UTC by yashikajotwani12

Added django version 3.2 and 4.0a1
, removed 2.2.0, updated some changes
that were required.

Fixes #122

2021-10-31 17:00 UTC, yashikajotwani12 commented
@nemesisdesign Please review. Thank you.

2021-11-11 16:28 UTC, nemesisdesign requested changes

2021-11-11 16:28 UTC, nemesisdesign commented on django_x509/base/admin.py
> +            path('x509/ca/(?P<pk>[^/]+).crl', self.crl_view, name='crl')
I think this will not work, `(?P<pk>[^/]+)` has to be converted to the new form of `path`, alternatively we can use `re_path`.

2021-12-01 21:38 UTC, nemesisdesign reviewed
I changed:

- django>=3.0.0,<=4.1.0 so we allow any version of django 4.0.x once released
- removed swapper because it's defined in openwisp-utils

2021-12-01 21:49 UTC, nemesisdesign approved these changes

2021-12-01 21:50 UTC, merged