Add an assertion in the tests hat checks the number of queries, comparing beforing and after this patch.
openwisp/django-x509 pull request #168
Opened 2024-12-12 20:50 UTC by SitaGanesh

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [x] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [x] I have updated the documentation.

## Reference to Existing Issue

Closes #167

## Description of Changes

Modified a test to the test_new function in test_cert.py to measure the number of database queries before and after the optimization. Ensuring that there should be at least 1 less query.

## Screenshot

![code](https://github.com/user-attachments/assets/9c42cb87-64ab-4332-943d-f6b1c62ae553)

2024-12-16 17:29 UTC, SitaGanesh commented
Sir @nemesifier, I would like to contribute to this organization, I believe I have made changes correctly as you have mentioned. I want to move forward in the next challenges that you assign me, I will do my best to tackle them by facing them. Could you guide me on what to do further to prove myself?

2024-12-23 13:04 UTC, nemesifier requested changes
Thank you for your patience @SItaGanesh! 

We've been busy completing some projects before Christmas and the End of the year and couldn't look into this yet.

Please see my comments below.

2024-12-23 13:04 UTC, nemesifier commented on django_x509/base/models.py
>          if generate:
```suggestion
```
Looks like we can simplify this further: remove these lines and any reference to the `generate` variable.

2024-12-23 14:00 UTC, nemesifier commented
I believe your understanding is correct, take your time. Ping us in the [dev chat](https://matrix.to/#/#openwisp_development:gitter.im) when ready.

2025-04-11 20:04 UTC, nemesifier submitted a review, later dismissed
I made some simplifications in https://github.com/openwisp/django-x509/pull/168/commits/ca31ca0040bb3325b37d4f2a7343f96841de4a91 and now is ready, thanks @SitaGanesh.

2025-04-11 20:05 UTC, merged

2025-04-12 04:53 UTC, SitaGanesh commented
Thank you, @nemesifier

I'm really happy to see the PR merged! 
Also, thank you for making the final simplifications—I’ve realized that I usually get stuck at those parts, which sometimes makes my initial attempts less successful. But I’m working on improving that, and I can already feel the difference as I try not to repeat the same mistakes. 

Right now, I'm exploring the issues on the next release board and feeling enthusiastic to tackle more! Looking forward to learning more and contributing further.